# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  ruby: circleci/ruby@0.1.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  test_on_ruby_latest:
    docker:
      - image: circleci/ruby
    executor: ruby/default
    steps:
      - checkout
      - run: 'ruby -v'
      - run: 'bundle install'
      - run: 'bundle exec rspec'
  test_on_ruby25:
    docker:
      - image: 'circleci/ruby:2.5'
    executor: ruby/default
    steps:
      - checkout
      - run: 'ruby -v'
      - run: 'bundle install'
      - run: 'bundle exec rspec'
  test_on_ruby21:
    docker:
      - image: 'circleci/ruby:2.1'
    executor: ruby/default
    steps:
      - checkout
      - run: 'ruby -v'
      - run: 'bundle install'
      - run: 'bundle exec rspec'

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - test_on_ruby21:
          context: rmega_secrets
      - test_on_ruby25:
          context: rmega_secrets
      - test_on_ruby_latest:
          context: rmega_secrets
